# Generated by Django 5.0.3 on 2026-07-07 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Attendance",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("date", models.DateField()),
                ("punch_in", models.TimeField()),
                ("punch_out", models.TimeField()),
                ("break_time", models.FloatField()),
                ("worktime", models.DecimalField(decimal_places=2, max_digits=5)),
                ("user_id", models.IntegerField()),
                ("is_compensated", models.IntegerField(default=0)),
                ("redeemed", models.IntegerField(default=0)),
                ("username", models.CharField(max_length=45)),
            ],
            options={
                "db_table": "tracker_attendance",
            },
        ),
        migrations.CreateModel(
            name="EmployeeDetails",
            fields=[
                ("employee_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("designation", models.CharField(max_length=100)),
                ("image", models.BinaryField(blank=True, null=True)),
                ("date_joined", models.DateField()),
                ("email", models.EmailField(blank=True, max_length=150, null=True)),
                (
                    "phone_number",
                    models.CharField(blank=True, max_length=15, null=True),
                ),
                ("department", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "salary",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("Active", "Active"), ("Inactive", "Inactive")],
                        default="Active",
                        max_length=10,
                    ),
                ),
                ("password", models.CharField(max_length=255)),
                ("authentication", models.CharField(max_length=50)),
                ("approval", models.JSONField(blank=True, null=True)),
                ("team_name", models.CharField(max_length=50)),
            ],
            options={
                "db_table": "employee_details",
            },
        ),
        migrations.CreateModel(
            name="Holiday",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("date", models.DateField()),
            ],
            options={
                "db_table": "tracker_holiday",
            },
        ),
        migrations.CreateModel(
            name="LeaveApplication",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("reason", models.CharField(max_length=255)),
                ("username", models.CharField(max_length=100)),
                ("approver", models.CharField(max_length=100)),
                ("leave_type", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("status", models.CharField(max_length=50)),
            ],
            options={
                "db_table": "tracker_leaveapplication",
            },
        ),
        migrations.CreateModel(
            name="ProjectTacker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=45, null=True)),
                ("to_aproove", models.JSONField(blank=True, null=True)),
                ("status", models.CharField(blank=True, max_length=45, null=True)),
                ("sender_name", models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                "db_table": "project_tacker",
            },
        ),
        migrations.CreateModel(
            name="TeamRanking",
            fields=[
                ("teamid", models.AutoField(primary_key=True, serialize=False)),
                ("team_name", models.CharField(max_length=100)),
                ("team_member", models.TextField()),
                ("date", models.DateField(auto_now=True)),
                ("speed_of_execution", models.IntegerField()),
                ("complaints_of_check_list", models.IntegerField()),
                ("task_ownership", models.IntegerField()),
                ("understanding_task", models.IntegerField()),
                ("quality_of_work", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="TrackerTasks",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("d_no", models.CharField(blank=True, max_length=50, null=True)),
                ("title", models.CharField(max_length=255)),
                ("projects", models.CharField(max_length=255)),
                ("scope", models.TextField(blank=True, null=True)),
                ("rev", models.CharField(blank=True, max_length=50, null=True)),
                ("task_status", models.CharField(blank=True, max_length=50, null=True)),
                ("category", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("Low", "Low"),
                            ("Medium", "Medium"),
                            ("High", "High"),
                        ],
                        default="Medium",
                        max_length=50,
                    ),
                ),
                ("start", models.DateField(blank=True, null=True)),
                ("end", models.DateField(blank=True, null=True)),
                ("group", models.CharField(blank=True, max_length=255, null=True)),
                ("assigned", models.CharField(blank=True, max_length=255, null=True)),
                ("checker", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "qc3_checker",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("review_3d", models.TextField(blank=True, null=True)),
                ("qc1", models.CharField(blank=True, max_length=50, null=True)),
                ("qc2", models.CharField(blank=True, max_length=50, null=True)),
                ("qc3", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "verification_status",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "phase_1_benchmark",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("task_benchmark", models.FloatField(blank=True, null=True)),
                ("mail_no", models.CharField(blank=True, max_length=50, null=True)),
                ("ref_no", models.CharField(blank=True, max_length=50, null=True)),
                ("list", models.CharField(blank=True, max_length=50, null=True)),
                ("date1", models.DateField(blank=True, null=True)),
                ("time", models.FloatField(blank=True, null=True)),
                ("comments", models.CharField(blank=True, max_length=1000, null=True)),
                (
                    "project_status",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("team", models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                "db_table": "tracker_project",
            },
        ),
    ]
