# Generated by Django 4.2.13 on 2026-10-06 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="attendance",
            options={
                "ordering": ["-date"],
                "verbose_name": "Attendance Record",
                "verbose_name_plural": "Attendance Records",
            },
        ),
        migrations.AlterModelOptions(
            name="employeedetails",
            options={
                "verbose_name": "Employee Detail",
                "verbose_name_plural": "Employee Details",
            },
        ),
        migrations.AlterModelOptions(
            name="holiday",
            options={
                "ordering": ["date"],
                "verbose_name": "Holiday",
                "verbose_name_plural": "Holidays",
            },
        ),
        migrations.AlterModelOptions(
            name="leaveapplication",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Leave Application",
                "verbose_name_plural": "Leave Applications",
            },
        ),
        migrations.AlterModelOptions(
            name="projecttacker",
            options={
                "verbose_name": "Project Tracker",
                "verbose_name_plural": "Project Trackers",
            },
        ),
        migrations.AlterModelOptions(
            name="teamranking",
            options={
                "ordering": ["-date"],
                "verbose_name": "Team Ranking",
                "verbose_name_plural": "Team Rankings",
            },
        ),
        migrations.AlterModelOptions(
            name="trackertasks",
            options={
                "verbose_name": "Tracker Task",
                "verbose_name_plural": "Tracker Tasks",
            },
        ),
        migrations.AddIndex(
            model_name="attendance",
            index=models.Index(fields=["username", "date"], name="idx_att_user_date"),
        ),
        migrations.AddIndex(
            model_name="attendance",
            index=models.Index(fields=["date"], name="idx_att_date"),
        ),
        migrations.AddIndex(
            model_name="trackertasks",
            index=models.Index(fields=["projects"], name="idx_task_project"),
        ),
        migrations.AddIndex(
            model_name="trackertasks",
            index=models.Index(fields=["date1"], name="idx_task_date1"),
        ),
        migrations.AddIndex(
            model_name="trackertasks",
            index=models.Index(fields=["assigned"], name="idx_task_assigned"),
        ),
        migrations.AddIndex(
            model_name="trackertasks",
            index=models.Index(fields=["team"], name="idx_task_team"),
        ),
    ]
